# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Code-Challenge-Yape' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Code-Challenge-Yape
  pod 'Alamofire', '~> 5.4'
  pod 'SwiftyJSON'
  pod 'GoogleMaps', '6.2.1'

end
